Updates made to customize for Skopos use; originally updated outside of git version-control, between Nov 2013 and Dec 16 2013

diff --git a/git-flow-hotfix b/git-flow-hotfix
--- a/git-flow-hotfix
+++ b/git-flow-hotfix
@@ -171,6 +171,7 @@ cmd_start() {
 		require_branches_equal "$MASTER_BRANCH" "$ORIGIN/$MASTER_BRANCH"
 	fi
 
+
 	# create branch
 	git checkout -b "$BRANCH" "$BASE"
 
@@ -178,9 +179,29 @@ cmd_start() {
 	echo "Summary of actions:"
 	echo "- A new branch '$BRANCH' was created, based on '$BASE'"
 	echo "- You are now on branch '$BRANCH'"
+
+	# increment hotfix patch-version
+	local toppom=$(get_top_pom_path)
+	if [ "$toppom" != "" ]; then
+		local curver=$(get_current_pom_version $toppom)
+		echo "curver = $curver"
+		curpatch=$(echo $curver | cut -d'.' -f3)
+		newpatch=$(expr $curpatch + 1)
+		newver="$(echo $curver | cut -d'.' -f1-2).$newpatch"
+
+		# Check if hotfix branch name jives with the expected pom version of hotfix
+		if [ "v${newver}" != "${VERSION}" ]; then
+			echo "WARN: Expected name of this hotfix branch to be v${newver}!"
+			# TODO: if $VERSION is of pattern v#.#.#, then we should get the newver value from $VERSION
+		fi
+
+		set_pom_version $toppom $newver
+	fi
+
+	git push "$ORIGIN" "$BRANCH"
+
 	echo
 	echo "Follow-up actions:"
-	echo "- Bump the version number now!"
 	echo "- Start committing your hot fixes"
 	echo "- When done, run:"
 	echo
@@ -193,7 +214,7 @@ cmd_finish() {
 	DEFINE_boolean sign false "sign the release tag cryptographically" s
 	DEFINE_string signingkey "" "use the given GPG-key for the digital signature (implies -s)" u
 	DEFINE_string message "" "use the given tag message" m
-	DEFINE_boolean push false "push to $ORIGIN after performing finish" p
+	DEFINE_boolean push true "push to $ORIGIN after performing finish" p
 	DEFINE_boolean keep false "keep branch after performing finish" k
 	DEFINE_boolean notag false "don't tag this release" n
 	parse_args "$@"
@@ -226,9 +247,11 @@ cmd_finish() {
 	if ! git_is_branch_merged_into "$BRANCH" "$MASTER_BRANCH"; then
 		git checkout "$MASTER_BRANCH" || \
 		  die "Could not check out $MASTER_BRANCH."
-		git merge --no-ff "$BRANCH" || \
-		  die "There were merge conflicts."
-		  # TODO: What do we do now?
+		if ! git merge --no-ff "$BRANCH"; then
+			echo "ERROR: There were merge conflicts on $MASTER_BRANCH!"
+			echo "Manually reconcile the conflicts on $MASTER_BRANCH and commit."
+			die "Please run finish again once above is done."
+		fi
 	fi
 
 	if noflag notag; then
@@ -240,10 +263,23 @@ cmd_finish() {
 			local opts="-a"
 			flag sign && opts="$opts -s"
 			[ "$FLAGS_signingkey" != "" ] && opts="$opts -u '$FLAGS_signingkey'"
-			[ "$FLAGS_message" != "" ] && opts="$opts -m '$FLAGS_message'"
-			git tag $opts "$VERSION_PREFIX$VERSION" || \
+			if [ "$FLAGS_message" != "" ]; then
+			       	opts="$opts -m '$FLAGS_message'"
+			else
+				opts="$opts -m 'Hot-fix Release'"
+			fi
+			(echo $opts $tagname | xargs git tag)  || \
 			die "Tagging failed. Please run finish again to retry."
 		fi
+	fi
+
+	# What is the pom version on the hotfix branch?
+	git checkout "$BRANCH"
+
+	local toppom=$(get_top_pom_path)
+	local hotpomver
+	if [ "$toppom" != "" ]; then
+		hotpomver=$(get_current_pom_version $toppom)
 	fi
 
 	# try to merge into develop
@@ -253,12 +289,34 @@ cmd_finish() {
 		git checkout "$DEVELOP_BRANCH" || \
 		  die "Could not check out $DEVELOP_BRANCH."
 
+		local devpomver
+		if [ "$toppom" != "" ]; then
+			devpomver=$(get_current_pom_version $toppom)
+			# Temporarily set dev pom-version to one from hotfix branch so that there are no
+			# merge conflicts on pom.
+			set_pom_version $toppom $hotpomver
+		fi
+
 		# TODO: Actually, accounting for 'git describe' pays, so we should
 		# ideally git merge --no-ff $tagname here, instead!
-		git merge --no-ff "$BRANCH" || \
-		  die "There were merge conflicts."
-		  # TODO: What do we do now?
+		if ! git merge --no-ff "$BRANCH"; then
+			echo "ERROR: There were merge conflicts on $DEVELOP_BRANCH!"
+			echo "Manually reconcile the conflicts on $DEVELOP_BRANCH and commit."
+			if [ "$hotpomver" != "$devpomver" ]; then
+				COMMIT_SET_POM_VERSION=0
+				set_pom_version $toppom $devpomver
+				unset COMMIT_SET_POM_VERSION
+			fi
+			die "Please run finish again once above is done."
+		fi
+
+		if [ "$toppom" != "" -a "$hotpomver" != "$devpomver" ]; then
+			set_pom_version $toppom $devpomver
+		fi
 	fi
+
+	# delete remote branch
+	git push "$ORIGIN" ":refs/heads/$BRANCH"
 
 	# delete branch
 	if noflag keep; then
@@ -285,9 +343,9 @@ cmd_finish() {
 	fi
 	echo "- Hotfix branch has been back-merged into '$DEVELOP_BRANCH'"
 	if flag keep; then
-		echo "- Hotfix branch '$BRANCH' is still available"
+		echo "- Hotfix branch '$BRANCH' is still available (locally)"
 	else
-		echo "- Hotfix branch '$BRANCH' has been deleted"
+		echo "- Hotfix branch '$BRANCH' has been deleted (both local and remote)"
 	fi
 	if flag push; then
 		echo "- '$DEVELOP_BRANCH', '$MASTER_BRANCH' and tags have been pushed to '$ORIGIN'"
diff --git a/git-flow-init b/git-flow-init
--- a/git-flow-init
+++ b/git-flow-init
@@ -294,6 +294,31 @@ cmd_default() {
 	fi
 
 
+	if flag force || \
+	  ! git config --get gitflow.skopos.devextn >/dev/null 2>&1; then
+		echo
+		echo "Skopos specific configuration:"
+		printf "Last four digits of your Skopos phone number? (enter nothing if you want to supply this via -N flag upon start of a feature) "
+		if noflag defaults; then
+			while read answer; do
+				if [ "$answer" != "" ]; then
+					if [ "$answer" -eq "$answer" ] 2>/dev/null; then
+						break
+					else
+						echo "error: Not a number" >&2
+						printf "Please enter last four digits of your Skopos phone number: "
+					fi
+				else
+					break
+				fi
+			done
+		else
+			printf "\n"
+		fi
+		[ "$answer" != "" ] && git config gitflow.skopos.devextn "$answer"
+
+	fi
+
 	# TODO: what to do with origin?
 }
 
diff --git a/git-flow-release b/git-flow-release
--- a/git-flow-release
+++ b/git-flow-release
@@ -174,10 +174,35 @@ cmd_start() {
 	echo
 	echo "Summary of actions:"
 	echo "- A new branch '$BRANCH' was created, based on '$BASE'"
+	
+	# increment develop versions to next-release version
+	local toppom=$(get_top_pom_path)
+	if [ "$toppom" != "" ]; then
+		git checkout "$BASE"
+
+		local curver=$(get_current_pom_version $toppom)
+		echo "Current version: " $curver
+		local curminor=$(echo $curver | cut -d'.' -f2)
+		local newver="$(echo $curver | cut -d'.' -f1).$(expr $curminor + 1).0"
+		set_pom_version $toppom $newver
+
+		git push "$ORIGIN" "$BASE"
+
+		git checkout "$BRANCH"
+	fi
+
+	git push "$ORIGIN" "$BRANCH"
+
+	echo "- Branch '$BRANCH' has been pushed to '$ORIGIN'"
+	if [ "$toppom" != "" ]; then
+		echo "- Branch '$BASE' has been pushed to '$ORIGIN'"
+	fi
 	echo "- You are now on branch '$BRANCH'"
+
+
 	echo
 	echo "Follow-up actions:"
-	echo "- Bump the version number now!"
+	echo "- Update release-notes, changelog, etc."
 	echo "- Start committing last-minute fixes in preparing your release"
 	echo "- When done, run:"
 	echo
@@ -190,7 +215,7 @@ cmd_finish() {
 	DEFINE_boolean sign false "sign the release tag cryptographically" s
 	DEFINE_string signingkey "" "use the given GPG-key for the digital signature (implies -s)" u
 	DEFINE_string message "" "use the given tag message" m
-	DEFINE_boolean push false "push to $ORIGIN after performing finish" p
+	DEFINE_boolean push true "push to $ORIGIN after performing finish" p
 	DEFINE_boolean keep false "keep branch after performing finish" k
 	DEFINE_boolean notag false "don't tag this release" n
 
@@ -224,9 +249,11 @@ cmd_finish() {
 	if ! git_is_branch_merged_into "$BRANCH" "$MASTER_BRANCH"; then
 		git checkout "$MASTER_BRANCH" || \
 		  die "Could not check out $MASTER_BRANCH."
-		git merge --no-ff "$BRANCH" || \
-		  die "There were merge conflicts."
-		  # TODO: What do we do now?
+		if ! git merge --no-ff "$BRANCH"; then
+			echo "ERROR: There were merge conflicts on $MASTER_BRANCH!"
+			echo "Manually reconcile the conflicts on $MASTER_BRANCH and commit."
+			die "Please run finish again once above is done."
+		fi
 	fi
 
 	if noflag notag; then
@@ -238,8 +265,12 @@ cmd_finish() {
 			local opts="-a"
 			flag sign && opts="$opts -s"
 			[ "$FLAGS_signingkey" != "" ] && opts="$opts -u '$FLAGS_signingkey'"
-			[ "$FLAGS_message" != "" ] && opts="$opts -m '$FLAGS_message'"
-			git tag $opts "$tagname" || \
+			if [ "$FLAGS_message" != "" ]; then
+			       	opts="$opts -m '$FLAGS_message'"
+			else
+				opts="$opts -m 'Release'"
+			fi
+			(echo $opts $tagname | xargs git tag)  || \
 			die "Tagging failed. Please run finish again to retry."
 		fi
 	fi
@@ -253,9 +284,11 @@ cmd_finish() {
 
 		# TODO: Actually, accounting for 'git describe' pays, so we should
 		# ideally git merge --no-ff $tagname here, instead!
-		git merge --no-ff "$BRANCH" || \
-		  die "There were merge conflicts."
-		  # TODO: What do we do now?
+		if ! git merge --no-ff "$BRANCH"; then
+			echo "ERROR: There were merge conflicts on $DEVELOP_BRANCH!"
+			echo "Manually reconcile the conflicts on $DEVELOP_BRANCH and commit."
+			die "Please run finish again once above is done."
+		fi
 	fi
 
 	# delete branch
diff --git a/gitflow-common b/gitflow-common
--- a/gitflow-common
+++ b/gitflow-common
@@ -310,3 +310,36 @@ require_branches_equal() {
 		fi
 	fi
 }
+
+#
+# Maven support commands
+#
+
+get_top_pom_path() {
+	local topdir=$(dirname $(git rev-parse --git-dir))
+	[ -f $topdir/pom.xml ] && echo $topdir/pom.xml;
+}
+
+get_current_pom_version() {
+	local toppom="$1"
+        mvn -f $toppom org.apache.maven.plugins:maven-help-plugin:2.1.1:evaluate -Dexpression=project.version 2>&1 | grep -E '^\d+(\.\d+)*(-.+)?$'
+}
+
+get_active_branch() {
+	git branch | grep '^* ' | cut -d' ' -f2
+}
+
+set_pom_version() {
+	local toppom="$1"
+	local newver="$2"
+	local curbranch=$(get_active_branch)
+	echo "Updating pom versions on $curbranch to $newver..."
+	if mvn -f $toppom versions:set -DnewVersion=$newver >/dev/null 2>&1; then
+		git add $(find $(dirname $toppom) -name pom.xml | grep -v '/target/') 
+		[ "$COMMIT_POM_SET_VERSION" != "0" ] && git commit -m "Updated pom versions on $curbranch to $newver"
+		echo "- POM versions on $curbranch have been updated to $newver"
+	else
+		echo "WARN: Unable to update pom versions on $curbranch to $newver";
+		echo "- Please fix/update pom versions on $curbranch manually."
+	fi
+}
