Merged changes made by rupigill to 'master' branch on fork (squashed & edited):     Release-start increments 2nd-least version number on develop IF release version does not have qualifier (e.g. a suffix after '_' or '-')     Release version supplied by user is used for pom.version, so it carries across run-time release info and nexus artifact naming.     Release-finish tags master w/out release-prefix     Feature start computes the feature-branch pom-version from the feature name.     gitflow inserted commit messages are prefixed with 'gitflow: '     Changed default value of 'fetch' to true; added -u to git push command in start so we start off tracking branch     Added distrib and installtar targets to Makefile     Fixed has() function and removed its use in places where we're expected to always have the expected remote branch

diff --git a/git-flow-hotfix b/git-flow-hotfix
--- a/git-flow-hotfix
+++ b/git-flow-hotfix
@@ -157,7 +157,7 @@ require_no_existing_hotfix_branches() {
 }
 
 cmd_start() {
-	DEFINE_boolean fetch false "fetch from $ORIGIN before performing finish" F
+	DEFINE_boolean fetch true "fetch from $ORIGIN before performing finish" F
 	parse_args "$@"
 	BASE=${2:-$MASTER_BRANCH}
 	require_version_arg
@@ -175,6 +175,7 @@ cmd_start() {
 		require_branches_equal "$MASTER_BRANCH" "$ORIGIN/$MASTER_BRANCH"
 	fi
 
+
 	# create branch
 	git_do checkout -b "$BRANCH" "$BASE"
 
@@ -182,9 +183,23 @@ cmd_start() {
 	echo "Summary of actions:"
 	echo "- A new branch '$BRANCH' was created, based on '$BASE'"
 	echo "- You are now on branch '$BRANCH'"
+
+	# increment hotfix patch-version
+	local toppom=$(get_top_pom_path)
+	if [ "$toppom" != "" ]; then
+		local curver=$(get_current_pom_version $toppom)
+		echo "curver = $curver"
+		curpatch=$(get_least_version $curver)
+		newpatch=$(expr $curpatch + 1)
+		newver=$(set_least_version $curver $newpatch)
+		newver=$(set_version_qualifier $newver "fix-SNAPSHOT")
+		set_pom_version $toppom $newver
+	fi
+
+	git push -u "$ORIGIN" "$BRANCH"
+
 	echo
 	echo "Follow-up actions:"
-	echo "- Bump the version number now!"
 	echo "- Start committing your hot fixes"
 	echo "- When done, run:"
 	echo
@@ -240,12 +255,12 @@ cmd_track() {
 }
 
 cmd_finish() {
-	DEFINE_boolean fetch false "fetch from $ORIGIN before performing finish" F
+	DEFINE_boolean fetch true "fetch from $ORIGIN before performing finish" F
 	DEFINE_boolean sign false "sign the release tag cryptographically" s
 	DEFINE_string signingkey "" "use the given GPG-key for the digital signature (implies -s)" u
 	DEFINE_string message "" "use the given tag message" m
 	DEFINE_string messagefile "" "use the contents of the given file as tag message" f
-	DEFINE_boolean push false "push to $ORIGIN after performing finish" p
+	DEFINE_boolean push true "push to $ORIGIN after performing finish" p
 	DEFINE_boolean keep false "keep branch after performing finish" k
 	DEFINE_boolean notag false "don't tag this release" n
 	parse_args "$@"
@@ -265,22 +280,34 @@ cmd_finish() {
 		git_do fetch -q "$ORIGIN" "$DEVELOP_BRANCH" || \
 		  die "Could not fetch $DEVELOP_BRANCH from $ORIGIN."
 	fi
-	if has "$ORIGIN/$MASTER_BRANCH" $(git_remote_branches); then
-		require_branches_equal "$MASTER_BRANCH" "$ORIGIN/$MASTER_BRANCH"
-	fi
-	if has "$ORIGIN/$DEVELOP_BRANCH" $(git_remote_branches); then
-		require_branches_equal "$DEVELOP_BRANCH" "$ORIGIN/$DEVELOP_BRANCH"
-	fi
+
+	require_branches_equal "$MASTER_BRANCH" "$ORIGIN/$MASTER_BRANCH"
+	require_branches_equal "$DEVELOP_BRANCH" "$ORIGIN/$DEVELOP_BRANCH"
 
 	# try to merge into master
 	# in case a previous attempt to finish this release branch has failed,
 	# but the merge into master was successful, we skip it now
 	if ! git_is_branch_merged_into "$BRANCH" "$MASTER_BRANCH"; then
+		echo "Removing qualifier from version before merging into master"
+		git_do checkout "$BRANCH"
+
+		local toppom=$(get_top_pom_path)
+		local hotpomver
+		if [ "$toppom" != "" ]; then
+			hotpomver=$(get_current_pom_version $toppom)
+		fi
+		set_pom_version $toppom $(set_version_qualifier $hotpomver "") "GITFLOW HOTFIX FINISH"
+
 		git_do checkout "$MASTER_BRANCH" || \
 		  die "Could not check out $MASTER_BRANCH."
-		git_do merge --no-ff "$BRANCH" || \
-		  die "There were merge conflicts."
-		  # TODO: What do we do now?
+		if ! git_do merge --no-ff "$BRANCH"; then
+			echo "ERROR: There were merge conflicts on $MASTER_BRANCH!"
+			echo "Manually reconcile the conflicts on $MASTER_BRANCH and commit."
+			die "Please run finish again once above is done."
+		fi
+	else
+		git_do checkout "$MASTER_BRANCH" || \
+		  die "Could not check out $MASTER_BRANCH."
 	fi
 
 	if noflag notag; then
@@ -292,9 +319,14 @@ cmd_finish() {
 			local opts="-a"
 			flag sign && opts="$opts -s"
 			[ "$FLAGS_signingkey" != "" ] && opts="$opts -u '$FLAGS_signingkey'"
-			[ "$FLAGS_message" != "" ] && opts="$opts -m '$FLAGS_message'"
-			[ "$FLAGS_messagefile" != "" ] && opts="$opts -F '$FLAGS_messagefile'"
-			eval git_do tag $opts "$VERSION_PREFIX$VERSION" "$BRANCH" || \
+			if [ "$FLAGS_message" != "" ]; then
+				opts="$opts -m '$FLAGS_message'"
+			elif [ "$FLAGS_messagefile" != "" ]; then
+				opts="$opts -F '$FLAGS_messagefile'"
+			else
+				opts="$opts -m 'Hot-fix Release'"
+			fi
+			(echo $opts $tagname | xargs git_do tag)  || \
 			die "Tagging failed. Please run finish again to retry."
 		fi
 	fi
@@ -306,27 +338,43 @@ cmd_finish() {
 		git_do checkout "$DEVELOP_BRANCH" || \
 		  die "Could not check out $DEVELOP_BRANCH."
 
+		local devtoppom=$(get_top_pom_path)
+		local devpomver
+		if [ "$devtoppom" != "" ]; then
+			devpomver=$(get_current_pom_version $devtoppom)
+			#TODO Detect if a Release was started/made on develop after hotfix started
+			git_do checkout "$BRANCH"
+			set_pom_version $toppom $devpomver "GITFLOW HOTFIX FINISH"
+			git_do checkout "$DEVELOP_BRANCH"
+		fi
+
 		# TODO: Actually, accounting for 'git describe' pays, so we should
 		# ideally git merge --no-ff $tagname here, instead!
-		git_do merge --no-ff "$BRANCH" || \
-		  die "There were merge conflicts."
-		  # TODO: What do we do now?
+		if ! git_do merge --no-ff "$BRANCH"; then
+			echo "ERROR: There were merge conflicts on $DEVELOP_BRANCH!"
+			echo "Manually reconcile the conflicts on $DEVELOP_BRANCH and commit."
+			die "Please run finish again once above is done."
+		fi
 	fi
 
-	# delete branch
+
 	if noflag keep; then
+		# delete remote branch
+		git_do push "$ORIGIN" ":refs/heads/$BRANCH"
+
+		# delete branch
 		git_do branch -d "$BRANCH"
 	fi
 
 	if flag push; then
-		git_do push "$ORIGIN" "$DEVELOP_BRANCH" || \
-			die "Could not push to $DEVELOP_BRANCH from $ORIGIN."
 		git_do push "$ORIGIN" "$MASTER_BRANCH" || \
 			die "Could not push to $MASTER_BRANCH from $ORIGIN."
 		if noflag notag; then
 			git_do push --tags "$ORIGIN" || \
 				die "Could not push tags to $ORIGIN."
 		fi
+		git_do push "$ORIGIN" "$DEVELOP_BRANCH" || \
+			die "Could not push to $DEVELOP_BRANCH from $ORIGIN."
 	fi
 
 	echo
@@ -338,9 +386,9 @@ cmd_finish() {
 	fi
 	echo "- Hotfix branch has been back-merged into '$DEVELOP_BRANCH'"
 	if flag keep; then
-		echo "- Hotfix branch '$BRANCH' is still available"
+		echo "- Hotfix branch '$BRANCH' was NOT deleted"
 	else
-		echo "- Hotfix branch '$BRANCH' has been deleted"
+		echo "- Hotfix branch '$BRANCH' was deleted (both local and remote)"
 	fi
 	if flag push; then
 		echo "- '$DEVELOP_BRANCH', '$MASTER_BRANCH' and tags have been pushed to '$ORIGIN'"
diff --git a/git-flow-release b/git-flow-release
--- a/git-flow-release
+++ b/git-flow-release
@@ -152,7 +152,7 @@ require_no_existing_release_branches() {
 }
 
 cmd_start() {
-	DEFINE_boolean fetch false "fetch from $ORIGIN before performing finish" F
+	DEFINE_boolean fetch true "fetch from $ORIGIN before performing finish" F
 	parse_args "$@"
 	BASE=${2:-$DEVELOP_BRANCH}
 	require_version_arg
@@ -166,9 +166,7 @@ cmd_start() {
 	if flag fetch; then
 		git_do fetch -q "$ORIGIN" "$DEVELOP_BRANCH"
 	fi
-	if has "$ORIGIN/$DEVELOP_BRANCH" $(git_remote_branches); then
-		require_branches_equal "$DEVELOP_BRANCH" "$ORIGIN/$DEVELOP_BRANCH"
-	fi
+	require_branches_equal "$DEVELOP_BRANCH" "$ORIGIN/$DEVELOP_BRANCH"
 
 	# create branch
 	git_do checkout -b "$BRANCH" "$BASE"
@@ -176,10 +174,40 @@ cmd_start() {
 	echo
 	echo "Summary of actions:"
 	echo "- A new branch '$BRANCH' was created, based on '$BASE'"
+	
+	local toppom=$(get_top_pom_path)
+	if [ "$toppom" != "" ]; then
+		# Change version on release branch
+		local newver=$(echo ${VERSION}-SNAPSHOT)
+		set_pom_version $toppom $newver
+
+		local qual=$(echo $VERSION | tr '_' '-' | cut -d '-' -f2-)
+		if [ "$qual" = "" ]; then
+			# increment develop versions to next-release version
+			git_do checkout "$BASE"
+
+			curver=$(get_current_pom_version $toppom)
+			echo "curver = $curver"
+			local curminor=$(get_2ndleast_version $curver)
+			newver=$(set_2ndleast_version $curver $(expr $curminor + 1))
+			set_pom_version $toppom $newver
+
+			git_do push "$ORIGIN" "$BASE"
+			echo "- Branch '$BASE' has been pushed to '$ORIGIN'"
+
+			git_do checkout "$BRANCH"
+		fi
+	fi
+
+
+	git_do push -u "$ORIGIN" "$BRANCH"
+
+	echo "- Branch '$BRANCH' has been pushed to '$ORIGIN'"
 	echo "- You are now on branch '$BRANCH'"
+
 	echo
 	echo "Follow-up actions:"
-	echo "- Bump the version number now!"
+	echo "- Update release-notes, changelog, etc."
 	echo "- Start committing last-minute fixes in preparing your release"
 	echo "- When done, run:"
 	echo
@@ -188,12 +216,12 @@ cmd_start() {
 }
 
 cmd_finish() {
-	DEFINE_boolean fetch false "fetch from $ORIGIN before performing finish" F
+	DEFINE_boolean fetch true "fetch from $ORIGIN before performing finish" F
 	DEFINE_boolean sign false "sign the release tag cryptographically" s
 	DEFINE_string signingkey "" "use the given GPG-key for the digital signature (implies -s)" u
 	DEFINE_string message "" "use the given tag message" m
 	DEFINE_string messagefile "" "use the contents of the given file as a tag message" f
-	DEFINE_boolean push false "push to $ORIGIN after performing finish" p
+	DEFINE_boolean push true "push to $ORIGIN after performing finish" p
 	DEFINE_boolean keep false "keep branch after performing finish" k
 	DEFINE_boolean notag false "don't tag this release" n
 	DEFINE_boolean squash false "squash release during merge" S
@@ -215,42 +243,61 @@ cmd_finish() {
 		git_do fetch -q "$ORIGIN" "$DEVELOP_BRANCH" || \
 		  die "Could not fetch $DEVELOP_BRANCH from $ORIGIN."
 	fi
-	if has "$ORIGIN/$MASTER_BRANCH" $(git_remote_branches); then
-		require_branches_equal "$MASTER_BRANCH" "$ORIGIN/$MASTER_BRANCH"
-	fi
-	if has "$ORIGIN/$DEVELOP_BRANCH" $(git_remote_branches); then
-		require_branches_equal "$DEVELOP_BRANCH" "$ORIGIN/$DEVELOP_BRANCH"
-	fi
+	require_branches_equal "$MASTER_BRANCH" "$ORIGIN/$MASTER_BRANCH"
+	require_branches_equal "$DEVELOP_BRANCH" "$ORIGIN/$DEVELOP_BRANCH"
 
 	# try to merge into master
 	# in case a previous attempt to finish this release branch has failed,
 	# but the merge into master was successful, we skip it now
 	if ! git_is_branch_merged_into "$BRANCH" "$MASTER_BRANCH"; then
+		echo "Removing SNAPSHOT qualifier from version before merging into master"
+		git_do checkout "$BRANCH"
+
+		local toppom=$(get_top_pom_path)
+		local relpomver
+		if [ "$toppom" != "" ]; then
+			relpomver=$(get_current_pom_version $toppom)
+			set_pom_version $toppom $(echo $relpomver | sed 's/-SNAPSHOT$//') "GITFLOW RELEASE FINISH"
+		fi
 		git_do checkout "$MASTER_BRANCH" || \
 		  die "Could not check out $MASTER_BRANCH."
 		if noflag squash; then
-			git_do merge --no-ff "$BRANCH" || \
-				die "There were merge conflicts."
-				# TODO: What do we do now?
+			if ! git_do merge --no-ff "$BRANCH"; then
+				echo "ERROR: There were merge conflicts on $MASTER_BRANCH!"
+				echo "Manually reconcile the conflicts on $MASTER_BRANCH and commit."
+				die "Please run finish again once above is done."
+			fi
 		else
-			git_do merge --squash "$BRANCH" || \
-				die "There were merge conflicts."
+			if ! git_do merge --squash "$BRANCH"; then
+				echo "ERROR: There were merge conflicts on $MASTER_BRANCH!"
+				echo "Manually reconcile the conflicts on $MASTER_BRANCH and commit."
+				die "Please run finish again once above is done."
+			fi
 			git_do commit
 		fi
+	else
+		git_do checkout "$MASTER_BRANCH" || \
+		  die "Could not check out $MASTER_BRANCH."
 	fi
 
 	if noflag notag; then
 		# try to tag the release
 		# in case a previous attempt to finish this release branch has failed,
 		# but the tag was set successful, we skip it now
-		local tagname=$VERSION_PREFIX$VERSION
+		#local tagname=$VERSION_PREFIX$VERSION
+		local tagname=$VERSION
 		if ! git_tag_exists "$tagname"; then
 			local opts="-a"
 			flag sign && opts="$opts -s"
 			[ "$FLAGS_signingkey" != "" ] && opts="$opts -u '$FLAGS_signingkey'"
-			[ "$FLAGS_message" != "" ] && opts="$opts -m '$FLAGS_message'"
-			[ "$FLAGS_messagefile" != "" ] && opts="$opts -F '$FLAGS_messagefile'"
-			eval git_do tag $opts "$tagname" "$BRANCH" || \
+			if [ "$FLAGS_message" != "" ]; then
+				opts="$opts -m '$FLAGS_message'"
+			elif [ "$FLAGS_messagefile" != "" ]; then
+				opts="$opts -F '$FLAGS_messagefile'"
+			else
+				opts="$opts -m 'Hot-fix Release'"
+			fi
+			(echo $opts $tagname | xargs git_do tag)  || \
 			die "Tagging failed. Please run finish again to retry."
 		fi
 	fi
@@ -262,22 +309,38 @@ cmd_finish() {
 		git_do checkout "$DEVELOP_BRANCH" || \
 		  die "Could not check out $DEVELOP_BRANCH."
 
+		local devtoppom=$(get_top_pom_path)
+		local devpomver
+		if [ "$devtoppom" != "" ]; then
+			devpomver=$(get_current_pom_version $devtoppom)
+			git_do checkout "$BRANCH"
+			set_pom_version $toppom $devpomver "GITFLOW RELEASE FINISH"
+			git_do checkout "$DEVELOP_BRANCH"
+		fi
+
 		# TODO: Actually, accounting for 'git describe' pays, so we should
 		# ideally git merge --no-ff $tagname here, instead!
 		if noflag squash; then
-			git_do merge --no-ff "$BRANCH" || \
-				die "There were merge conflicts."
-				# TODO: What do we do now?
+			if ! git_do merge --no-ff "$BRANCH"; then
+				echo "ERROR: There were merge conflicts on $DEVELOP_BRANCH!"
+				echo "Manually reconcile the conflicts on $DEVELOP_BRANCH and commit."
+				die "Please run finish again once above is done."
+			fi
 		else
-			git_do merge --squash "$BRANCH" || \
-				die "There were merge conflicts."
-				# TODO: What do we do now?
+			if ! git_do merge --squash "$BRANCH"; then
+				echo "ERROR: There were merge conflicts on $DEVELOP_BRANCH!"
+				echo "Manually reconcile the conflicts on $DEVELOP_BRANCH and commit."
+				die "Please run finish again once above is done."
+			fi
 			git_do commit
 		fi
 	fi
 
 	# delete branch
 	if noflag keep; then
+		# delete remote branch
+		git_do push "$ORIGIN" :"$BRANCH"
+
 		if [ "$BRANCH" = "$(git_current_branch)" ]; then
 			git_do checkout "$MASTER_BRANCH"
 		fi
@@ -285,16 +348,14 @@ cmd_finish() {
 	fi
 
 	if flag push; then
-		git_do push "$ORIGIN" "$DEVELOP_BRANCH" || \
-			die "Could not push to $DEVELOP_BRANCH from $ORIGIN."
 		git_do push "$ORIGIN" "$MASTER_BRANCH" || \
 			die "Could not push to $MASTER_BRANCH from $ORIGIN."
 		if noflag notag; then
 			git_do push --tags "$ORIGIN" || \
 			  die "Could not push tags to $ORIGIN."
 		fi
-		git_do push "$ORIGIN" :"$BRANCH" || \
-			die "Could not delete the remote $BRANCH in $ORIGIN."
+		git_do push "$ORIGIN" "$DEVELOP_BRANCH" || \
+			die "Could not push to $DEVELOP_BRANCH from $ORIGIN."
 	fi
 
 	echo
@@ -306,13 +367,12 @@ cmd_finish() {
 	fi
 	echo "- Release branch has been back-merged into '$DEVELOP_BRANCH'"
 	if flag keep; then
-		echo "- Release branch '$BRANCH' is still available"
+		echo "- Release branch '$BRANCH' was NOT deleted"
 	else
-		echo "- Release branch '$BRANCH' has been deleted"
+		echo "- Release branch '$BRANCH' was deleted (both local and remote)"
 	fi
 	if flag push; then
 		echo "- '$DEVELOP_BRANCH', '$MASTER_BRANCH' and tags have been pushed to '$ORIGIN'"
-		echo "- Release branch '$BRANCH' in '$ORIGIN' has been deleted."
 	fi
 	echo
 }
diff --git a/gitflow-common b/gitflow-common
--- a/gitflow-common
+++ b/gitflow-common
@@ -51,7 +51,7 @@ escape() {
 # set logic
 has() {
 	local item=$1; shift
-	echo " $@ " | grep -q " $(escape $item) "
+	echo "$@" | grep -qwF "$item"
 }
 
 # basic math
@@ -322,5 +322,84 @@ require_branches_equal() {
 		else
 			die "Branches need merging first."
 		fi
+	fi
+}
+
+#
+# Maven support commands
+#
+
+get_top_pom_path() {
+	local topdir=$(dirname $(git rev-parse --git-dir))
+	[ -f $topdir/pom.xml ] && echo $topdir/pom.xml;
+}
+
+get_current_pom_version() {
+	local toppom="$1"
+        mvn -o -f $toppom org.apache.maven.plugins:maven-help-plugin:2.1.1:evaluate -Dexpression=project.version 2>&1 | grep -E '^\d+(\.\d+)*(-.+)?$'
+}
+
+get_active_branch() {
+	git branch | grep '^* ' | cut -d' ' -f2
+}
+
+get_2ndleast_version() {
+	local v="$1"
+        echo $v | cut -d'-' -f1 | awk -F. '{print $(NF-1)}' 
+}
+
+set_2ndleast_version() {
+	local newval="$2"
+	echo $1 | sed -E 's/[[:digit:]]+\.([[:digit:]]+)(-.+)?$/'$newval'.\1\2/'
+}
+
+get_least_version() {
+	echo $1 | cut -d'-' -f1 | awk -F. '{print $NF}'
+}
+
+set_least_version() {
+	local newval="$2"
+	echo $1 | sed -E 's/\.[[:digit:]]+(-.+)?$/.'$newval'\1/'
+}
+
+get_version_qualifier() {
+	echo $1 | cut -d'-' -f2-
+}
+
+set_version_qualifier() {
+	local qual
+	if [ "$2" != "" ]; then
+		qual="-$2"
+	else
+		qual=""
+	fi
+	echo $1 | sed -E 's/(-.+)?$/'$qual'/'
+}
+
+remove_version_qualifier() {
+	echo $1 | sed -E 's/-.+$//'
+}
+
+set_pom_version() {
+	local toppom="$1"
+	local newver="$2"
+	local curbranch=$(get_active_branch)
+	local newver_mod="$newver"
+	echo "Updating pom versions on $curbranch to $newver..."
+	if [ "$(echo $newver | grep -E '\${revision}$')" != "" ]; then
+		newver_mod=$(echo $newver | sed -E 's/-\$\{revision\}$/-VERSION_REVISION_PLACEHOLDER/')
+	fi
+	if mvn -o -f $toppom versions:set -DgenerateBackupPoms=false -DnewVersion=$newver_mod -DprocessDependencies=false -DprocessPlugins=false -DprocessParent=true -DupdateMatchingVersions=true >/dev/null 2>&1; then
+		if [ "$newver_mod" != "$newver" ]; then
+			for f in $(grep -l VERSION_REVISION_PLACEHOLDER $(find $(dirname $toppom) -name pom.xml)); do
+				sed -E 's/-VERSION_REVISION_PLACEHOLDER/-${revision}/g' $f > ${f}.gitflow && mv ${f}.gitflow $f
+			done
+		fi
+		git add $(find $(dirname $toppom) -name pom.xml | grep -v '/target/') 
+		[ "$COMMIT_POM_SET_VERSION" != "0" ] && git commit -m "gitflow: Updated pom versions on $curbranch to $newver"
+		echo "- POM versions on $curbranch have been updated to $newver"
+	else
+		echo "WARN: Unable to update pom versions on $curbranch to $newver";
+		echo "- Please fix/update pom versions on $curbranch manually."
 	fi
 }
